# Generated by Django 4.2.3 on 2023-07-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task5app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
